import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const alice = await prisma.user.upsert({
    where: { email: 'alice@prisma.io' },
    update: {},
    create: {
      email: 'alice@prisma.io',
      name: 'Alice',
      password: 'whoami',
      profile: {
        create: {
          bio: 'I like turtles',
        },
      },
    },
  });
  const bob = await prisma.user.upsert({
    where: { email: 'bob@prisma.io' },
    update: {},
    create: {
      email: 'bob@prisma.io',
      name: 'Bob',
      password: 'whoami',
      profile: {
        create: {
          bio: 'blue eyes',
        },
      },
    },
  });
  const ariadne = await prisma.user.upsert({
    where: { email: 'ariadne@prisma.io' },
    update: {},
    create: {
      email: 'ariadne@prisma.io',
      name: 'Ariadne',
      password: 'whoami',
      profile: {
        create: {
          bio: 'very smart',
        },
      },
    },
  });
  console.log({ alice, bob, ariadne });

  const regions = await prisma.region.createMany({
    data: [
      { id: 1, name: 'Europe' },
      { id: 2, name: 'America' },
      { id: 3, name: 'Asia' },
      { id: 4, name: 'Middle East and Africa' },
    ],
    skipDuplicates: true,
  });

  const countries = await prisma.country.createMany({
    data: [
      { id: 'IT', name: 'Italy', regionId: 1 },
      { id: 'US', name: 'United States of America', regionId: 2 },
      { id: 'JP', name: 'Japan', regionId: 3 },
      { id: 'CA', name: 'Canada', regionId: 2 },
      { id: 'CN', name: 'China', regionId: 3 },
      { id: 'IN', name: 'India', regionId: 3 },
      { id: 'AU', name: 'Australia', regionId: 3 },
      { id: 'ZW', name: 'Zimbabwe', regionId: 4 },
      { id: 'SG', name: 'Singapore', regionId: 3 },
      { id: 'UK', name: 'United Kingdom', regionId: 1 },
      { id: 'FR', name: 'France', regionId: 1 },
      { id: 'DE', name: 'Germany', regionId: 1 },
      { id: 'ZM', name: 'Zambia', regionId: 4 },
      { id: 'BR', name: 'Brazil', regionId: 2 },
      { id: 'CH', name: 'Switzerland', regionId: 1 },
      { id: 'NL', name: 'Netherlands', regionId: 1 },
      { id: 'MX', name: 'Mexico', regionId: 2 },
      { id: 'KW', name: 'Kuwait', regionId: 4 },
      { id: 'IL', name: 'Israel', regionId: 4 },
      { id: 'DK', name: 'Denmark', regionId: 1 },
      { id: 'HK', name: 'HongKong', regionId: 3 },
      { id: 'NG', name: 'Nigeria', regionId: 4 },
      { id: 'AR', name: 'Argentina', regionId: 2 },
      { id: 'BE', name: 'Belgium', regionId: 1 },
      { id: 'NO', name: 'Norway', regionId: 1 },
      { id: 'EG', name: 'Egypt', regionId: 4 },
      { id: 'TN', name: 'Tunisia', regionId: 4 },
      { id: 'JM', name: 'Jamaica', regionId: 2 },
      { id: 'CL', name: 'Chile', regionId: 2 },
      { id: 'IR', name: 'Iran', regionId: 4 },
      { id: 'IQ', name: 'Iraq', regionId: 4 },
      { id: 'SY', name: 'Syria', regionId: 4 },
      { id: 'SA', name: 'Saudi Arabia', regionId: 4 },
      { id: 'YE', name: 'Yemen', regionId: 4 },
      { id: 'QA', name: 'Qatar', regionId: 4 },
      { id: 'BH', name: 'Bahrain', regionId: 4 },
      { id: 'AE', name: 'United Arab Emirates', regionId: 4 },
      { id: 'OM', name: 'Oman', regionId: 4 },
      { id: 'TR', name: 'Turkey', regionId: 4 },
    ],
    skipDuplicates: true,
  });

  const locations = await prisma.location.createMany({
    data: [
      {
        id: 1000,
        streetAddress: '1297 Via Cola di Rie',
        postalCode: '00989',
        city: 'Rome',
        countryId: 'IT',
      },
      {
        id: 1100,
        streetAddress: '93091 Calle della Testa',
        postalCode: '10934',
        city: 'Venice',
        countryId: 'IT',
      },
      {
        id: 1200,
        streetAddress: '2017 Shinjuku-ku',
        postalCode: '1689',
        city: 'Tokyo',
        stateProvince: 'Tokyo Prefecture',
        countryId: 'JP',
      },
      {
        id: 1300,
        streetAddress: '9450 Kamiya-cho',
        postalCode: '6823',
        city: 'Hiroshima',
        countryId: 'JP',
      },
      {
        id: 1400,
        streetAddress: '2014 Jabberwocky Rd',
        postalCode: '26192',
        city: 'Southlake',
        stateProvince: 'Texas',
        countryId: 'US',
      },
      {
        id: 1500,
        streetAddress: '2011 Interiors Blvd',
        postalCode: '99236',
        city: 'South San Francisco',
        stateProvince: 'California',
        countryId: 'US',
      },
      {
        id: 1600,
        streetAddress: '2007 Zagora St',
        postalCode: '50090',
        city: 'South Brunswick',
        stateProvince: 'New Jersey',
        countryId: 'US',
      },
      {
        id: 1700,
        streetAddress: '2004 Charade Rd',
        postalCode: '98199',
        city: 'Seattle',
        stateProvince: 'Washington',
        countryId: 'US',
      },
      {
        id: 1800,
        streetAddress: '147 Spadina Ave',
        postalCode: 'M5V 2L7',
        city: 'Toronto',
        stateProvince: 'Ontario',
        countryId: 'CA',
      },
      {
        id: 1900,
        streetAddress: '6092 Boxwood St',
        postalCode: 'YSW 9T2',
        city: 'Whitehorse',
        stateProvince: 'Yukon',
        countryId: 'CA',
      },
      {
        id: 2000,
        streetAddress: '40-5-12 Laogianggen',
        postalCode: '190518',
        city: 'Beijing',
        countryId: 'CN',
      },
      {
        id: 2100,
        streetAddress: '1298 Vileparle (E)',
        postalCode: '490231',
        city: 'Bombay',
        stateProvince: 'Maharashtra',
        countryId: 'IN',
      },
      {
        id: 2200,
        streetAddress: '12-98 Victoria Street',
        postalCode: '2901',
        city: 'Sydney',
        stateProvince: 'New South Wales',
        countryId: 'AU',
      },
      {
        id: 2300,
        streetAddress: '198 Clementi North',
        postalCode: '540198',
        city: 'Singapore',
        countryId: 'SG',
      },
      {
        id: 2400,
        streetAddress: '8204 Arthur St',
        postalCode: 'Y9722',
        city: 'London',
        countryId: 'UK',
      },
      {
        id: 2500,
        streetAddress: 'Magdalen Centre, The Oxford Science Park',
        postalCode: 'OX9 9ZB',
        city: 'Oxford',
        stateProvince: 'Oxford',
        countryId: 'UK',
      },
      {
        id: 2600,
        streetAddress: '9702 Chester Road',
        postalCode: '962985015',
        city: 'Stretford',
        stateProvince: 'Manchester',
        countryId: 'UK',
      },
      {
        id: 2700,
        streetAddress: 'Schwanthalerstr. 7031',
        postalCode: '80925',
        city: 'Munich',
        stateProvince: 'Bavaria',
        countryId: 'DE',
      },
      {
        id: 2800,
        streetAddress: 'Rua Frei Caneca 1360',
        postalCode: '01307-002',
        city: 'Sao Paulo',
        stateProvince: 'Sao Paulo',
        countryId: 'BR',
      },
      {
        id: 2900,
        streetAddress: '20 Rue des Corps-Saints',
        postalCode: '1730',
        city: 'Geneva',
        stateProvince: 'Geneve',
        countryId: 'CH',
      },
      {
        id: 3000,
        streetAddress: 'Murtenstrasse 921',
        postalCode: '3095',
        city: 'Bern',
        stateProvince: 'BE',
        countryId: 'CH',
      },
      {
        id: 3100,
        streetAddress: 'Pieter Breughelstraat 837',
        postalCode: '3029SK',
        city: 'Utrecht',
        stateProvince: 'Utrecht',
        countryId: 'NL',
      },
      {
        id: 3200,
        streetAddress: 'Mariano Escobedo 9991',
        postalCode: '11932',
        city: 'Mexico City',
        stateProvince: 'Distrito Federal,',
        countryId: 'MX',
      },
    ],
    skipDuplicates: true,
  });

  const jobs = await prisma.job.createMany({
    data: [
      { id: 'AD_PRES', title: 'President', minSalary: 20000, maxSalary: 40000 },
      {
        id: 'AD_VP',
        title: 'Administration Vice President',
        minSalary: 15000,
        maxSalary: 30000,
      },
      {
        id: 'AD_ASST',
        title: 'Administration Assistant',
        minSalary: 3000,
        maxSalary: 6000,
      },
      {
        id: 'AC_MGR',
        title: 'Accounting Manager',
        minSalary: 8200,
        maxSalary: 16000,
      },
      {
        id: 'AC_ACCOUNT',
        title: 'Public Accountant',
        minSalary: 4200,
        maxSalary: 9000,
      },
      {
        id: 'SA_MAN',
        title: 'Sales Manager',
        minSalary: 10000,
        maxSalary: 20000,
      },
      {
        id: 'SA_REP',
        title: 'Sales Representative',
        minSalary: 6000,
        maxSalary: 12000,
      },
      {
        id: 'PU_MAN',
        title: 'Purchasing Manager',
        minSalary: 8000,
        maxSalary: 15000,
      },
      {
        id: 'PU_CLERK',
        title: 'Purchasing Clerk',
        minSalary: 2500,
        maxSalary: 5500,
      },
      {
        id: 'ST_MAN',
        title: 'Stock Manager',
        minSalary: 5500,
        maxSalary: 8500,
      },
      {
        id: 'ST_CLERK',
        title: 'Stock Clerk',
        minSalary: 2000,
        maxSalary: 5000,
      },
      {
        id: 'SH_CLERK',
        title: 'Shipping Clerk',
        minSalary: 2500,
        maxSalary: 5500,
      },
      { id: 'IT_PROG', title: 'Programmer', minSalary: 4000, maxSalary: 10000 },
      {
        id: 'MK_MAN',
        title: 'Marketing Manager',
        minSalary: 9000,
        maxSalary: 15000,
      },
      {
        id: 'MK_REP',
        title: 'Marketing Representative',
        minSalary: 4000,
        maxSalary: 9000,
      },
      {
        id: 'HR_REP',
        title: 'Human Resources Representative',
        minSalary: 4000,
        maxSalary: 9000,
      },
      {
        id: 'PR_REP',
        title: 'Public Relations Representative',
        minSalary: 4500,
        maxSalary: 10500,
      },
      {
        id: 'FI_MGR',
        title: 'Finance Manager',
        minSalary: 8200,
        maxSalary: 16000,
      },
      {
        id: 'FI_ACCOUNT',
        title: 'Accountant',
        minSalary: 4200,
        maxSalary: 9000,
      },
    ],
    skipDuplicates: true,
  });

  const departments = await prisma.department.createMany({
    data: [
      { id: 10, name: 'Administration', locationId: 1700 },
      { id: 20, name: 'Marketing', locationId: 1800 },
      { id: 30, name: 'Purchasing', locationId: 1700 },
      { id: 40, name: 'Human Resources', locationId: 2400 },
      { id: 50, name: 'Shipping', locationId: 1500 },
      { id: 60, name: 'IT', locationId: 1400 },
      { id: 70, name: 'Public Relations', locationId: 2700 },
      { id: 80, name: 'Sales', locationId: 2500 },
      { id: 90, name: 'Executive', locationId: 1700 },
      { id: 100, name: 'Finance', locationId: 1700 },
      { id: 110, name: 'Accounting', locationId: 1700 },
      { id: 120, name: 'Treasury', locationId: 1700 },
      { id: 130, name: 'Corporate Tax', locationId: 1700 },
      {
        id: 140,
        name: 'Control And Credit',
        locationId: 1700,
      },
      {
        id: 150,
        name: 'Shareholder Services',
        locationId: 1700,
      },
      { id: 160, name: 'Benefits', locationId: 1700 },
      { id: 170, name: 'Manufacturing', locationId: 1700 },
      { id: 180, name: 'Construction', locationId: 1700 },
      { id: 190, name: 'Contracting', locationId: 1700 },
      { id: 200, name: 'Operations', locationId: 1700 },
      { id: 210, name: 'IT Support', locationId: 1700 },
      { id: 220, name: 'NOC', locationId: 1700 },
      { id: 230, name: 'IT Helpdesk', locationId: 1700 },
      { id: 240, name: 'Government Sales', locationId: 1700 },
      { id: 250, name: 'Retail Sales', locationId: 1700 },
      { id: 260, name: 'Recruiting', locationId: 1700 },
      { id: 270, name: 'Payroll', locationId: 1700 },
    ],
    skipDuplicates: true,
  });

  const employees = await prisma.employee.createMany({
    data: [
      {
        id: 100,
        firstName: 'Steven',
        lastName: 'King',
        email: 'steven.king@prisma.io',
        phone: '515.123.4567',
        hiredAt: new Date('1987-06-17'),
        jobId: 'AD_PRES',
        salary: 24000,
        departmentId: 90,
      },
      {
        id: 101,
        firstName: 'Neena',
        lastName: 'Kochhar',
        email: 'neena.kochhar@prisma.io',
        phone: '515.123.4568',
        hiredAt: new Date('1989-09-21'),
        jobId: 'AD_VP',
        salary: 17000,
        managerId: 100,
        departmentId: 90,
      },
      {
        id: 102,
        firstName: 'Lex',
        lastName: 'De Haan',
        email: 'lex.dehaan@prisma.io',
        phone: '515.123.4569',
        hiredAt: new Date('1993-01-13'),
        jobId: 'AD_VP',
        salary: 17000,
        managerId: 100,
        departmentId: 90,
      },
      {
        id: 103,
        firstName: 'Alexander',
        lastName: 'Hunold',
        email: 'alexander.hunold@prisma.io',
        phone: '590.423.4567',
        hiredAt: new Date('1990-01-03'),
        jobId: 'IT_PROG',
        salary: 9000,
        managerId: 102,
        departmentId: 60,
      },
      {
        id: 104,
        firstName: 'Bruce',
        lastName: 'Ernst',
        email: 'bruce.ernst@prisma.io',
        phone: '590.423.4568',
        hiredAt: new Date('1991-05-21'),
        jobId: 'IT_PROG',
        salary: 6000,
        managerId: 103,
        departmentId: 60,
      },
      {
        id: 105,
        firstName: 'David',
        lastName: 'Austin',
        email: 'david.austin@prisma.io',
        phone: '590.423.4569',
        hiredAt: new Date('1997-06-25'),
        jobId: 'IT_PROG',
        salary: 4800,
        managerId: 103,
        departmentId: 60,
      },
      {
        id: 106,
        firstName: 'Valli',
        lastName: 'Pataballa',
        email: 'valli.pataballa@prisma.io',
        phone: '590.423.4560',
        hiredAt: new Date('1998-02-05'),
        jobId: 'IT_PROG',
        salary: 4800,
        managerId: 103,
        departmentId: 60,
      },
      {
        id: 107,
        firstName: 'Diana',
        lastName: 'Lorentz',
        email: 'diana.lorentz@prisma.io',
        phone: '590.423.5567',
        hiredAt: new Date('1999-02-07'),
        jobId: 'IT_PROG',
        salary: 4200,
        managerId: 103,
        departmentId: 60,
      },
      {
        id: 108,
        firstName: 'Nancy',
        lastName: 'Greenberg',
        email: 'nancy.greenberg@prisma.io',
        phone: '515.124.4569',
        hiredAt: new Date('1994-08-17'),
        jobId: 'FI_MGR',
        salary: 12000,
        managerId: 101,
        departmentId: 100,
      },
      {
        id: 109,
        firstName: 'Daniel',
        lastName: 'Faviet',
        email: 'daniel.faviet@prisma.io',
        phone: '515.124.4169',
        hiredAt: new Date('1994-08-16'),
        jobId: 'FI_ACCOUNT',
        salary: 9000,
        managerId: 108,
        departmentId: 100,
      },
      {
        id: 110,
        firstName: 'John',
        lastName: 'Chen',
        email: 'john.chen@prisma.io',
        phone: '515.124.4269',
        hiredAt: new Date('1997-09-28'),
        jobId: 'FI_ACCOUNT',
        salary: 8200,
        managerId: 108,
        departmentId: 100,
      },
      {
        id: 111,
        firstName: 'Ismael',
        lastName: 'Sciarra',
        email: 'ismael.sciarra@prisma.io',
        phone: '515.124.4369',
        hiredAt: new Date('1997-09-30'),
        jobId: 'FI_ACCOUNT',
        salary: 7700,
        managerId: 108,
        departmentId: 100,
      },
      {
        id: 112,
        firstName: 'Jose Manuel',
        lastName: 'Urman',
        email: 'josemanuel.urman@prisma.io',
        phone: '515.124.4469',
        hiredAt: new Date('1998-03-07'),
        jobId: 'FI_ACCOUNT',
        salary: 7800,
        managerId: 108,
        departmentId: 100,
      },
      {
        id: 113,
        firstName: 'Luis',
        lastName: 'Popp',
        email: 'luis.popp@prisma.io',
        phone: '515.124.4567',
        hiredAt: new Date('1999-12-07'),
        jobId: 'FI_ACCOUNT',
        salary: 6900,
        managerId: 108,
        departmentId: 100,
      },
      {
        id: 114,
        firstName: 'Den',
        lastName: 'Raphaely',
        email: 'den.raphaely@prisma.io',
        phone: '515.127.4561',
        hiredAt: new Date('1994-12-07'),
        jobId: 'PU_MAN',
        salary: 11000,
        managerId: 100,
        departmentId: 30,
      },
      {
        id: 115,
        firstName: 'Alexander',
        lastName: 'Khoo',
        email: 'alexander.khoo@prisma.io',
        phone: '515.127.4562',
        hiredAt: new Date('1995-05-18'),
        jobId: 'PU_CLERK',
        salary: 3100,
        managerId: 114,
        departmentId: 30,
      },
      {
        id: 116,
        firstName: 'Shelli',
        lastName: 'Baida',
        email: 'shelli.baida@prisma.io',
        phone: '515.127.4563',
        hiredAt: new Date('1997-12-24'),
        jobId: 'PU_CLERK',
        salary: 2900,
        managerId: 114,
        departmentId: 30,
      },
      {
        id: 117,
        firstName: 'Sigal',
        lastName: 'Tobias',
        email: 'sigal.tobias@prisma.io',
        phone: '515.127.4564',
        hiredAt: new Date('1997-07-24'),
        jobId: 'PU_CLERK',
        salary: 2800,
        managerId: 114,
        departmentId: 30,
      },
      {
        id: 118,
        firstName: 'Guy',
        lastName: 'Himuro',
        email: 'guy.himuro@prisma.io',
        phone: '515.127.4565',
        hiredAt: new Date('1998-11-15'),
        jobId: 'PU_CLERK',
        salary: 2600,
        managerId: 114,
        departmentId: 30,
      },
      {
        id: 119,
        firstName: 'Karen',
        lastName: 'Colmenares',
        email: 'karen.colmenares@prisma.io',
        phone: '515.127.4566',
        hiredAt: new Date('1999-08-10'),
        jobId: 'PU_CLERK',
        salary: 2500,
        managerId: 114,
        departmentId: 30,
      },
      {
        id: 120,
        firstName: 'Matthew',
        lastName: 'Weiss',
        email: 'matthew.weiss@prisma.io',
        phone: '650.123.1234',
        hiredAt: new Date('1996-07-18'),
        jobId: 'ST_MAN',
        salary: 8000,
        managerId: 100,
        departmentId: 50,
      },
      {
        id: 121,
        firstName: 'Adam',
        lastName: 'Fripp',
        email: 'adam.fripp@prisma.io',
        phone: '650.123.2234',
        hiredAt: new Date('1997-04-10'),
        jobId: 'ST_MAN',
        salary: 8200,
        managerId: 100,
        departmentId: 50,
      },
      {
        id: 122,
        firstName: 'Payam',
        lastName: 'Kaufling',
        email: 'payam.kaufling@prisma.io',
        phone: '650.123.3234',
        hiredAt: new Date('1995-05-01'),
        jobId: 'ST_MAN',
        salary: 7900,
        managerId: 100,
        departmentId: 50,
      },
      {
        id: 123,
        firstName: 'Shanta',
        lastName: 'Vollman',
        email: 'shanta.vollman@prisma.io',
        phone: '650.123.4234',
        hiredAt: new Date('1997-10-10'),
        jobId: 'ST_MAN',
        salary: 6500,
        managerId: 100,
        departmentId: 50,
      },
      {
        id: 124,
        firstName: 'Kevin',
        lastName: 'Mourgos',
        email: 'kevin.mourgos@prisma.io',
        phone: '650.123.5234',
        hiredAt: new Date('1999-11-16'),
        jobId: 'ST_MAN',
        salary: 5800,
        managerId: 100,
        departmentId: 50,
      },
      {
        id: 125,
        firstName: 'Julia',
        lastName: 'Nayer',
        email: 'julia.nayer@prisma.io',
        phone: '650.124.1214',
        hiredAt: new Date('1997-07-16'),
        jobId: 'ST_CLERK',
        salary: 3200,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 126,
        firstName: 'Irene',
        lastName: 'Mikkilineni',
        email: 'irene.mikkilineni@prisma.io',
        phone: '650.124.1224',
        hiredAt: new Date('1998-09-28'),
        jobId: 'ST_CLERK',
        salary: 2700,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 127,
        firstName: 'James',
        lastName: 'Landry',
        email: 'james.landry@prisma.io',
        phone: '650.124.1334',
        hiredAt: new Date('1999-01-14'),
        jobId: 'ST_CLERK',
        salary: 2400,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 128,
        firstName: 'Steven',
        lastName: 'Markle',
        email: 'steven.markle@prisma.io',
        phone: '650.124.1434',
        hiredAt: new Date('2000-03-08'),
        jobId: 'ST_CLERK',
        salary: 2200,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 129,
        firstName: 'Laura',
        lastName: 'Bissot',
        email: 'laura.bissot@prisma.io',
        phone: '650.124.5234',
        hiredAt: new Date('1997-08-20'),
        jobId: 'ST_CLERK',
        salary: 3300,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 130,
        firstName: 'Mozhe',
        lastName: 'Atkinson',
        email: 'mozhe.atkinson@prisma.io',
        phone: '650.124.6234',
        hiredAt: new Date('1997-10-30'),
        jobId: 'ST_CLERK',
        salary: 2800,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 131,
        firstName: 'James',
        lastName: 'Marlow',
        email: 'james.marlow@prisma.io',
        phone: '650.124.7234',
        hiredAt: new Date('1998-02-16'),
        jobId: 'ST_CLERK',
        salary: 2500,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 132,
        firstName: 'TJ',
        lastName: 'Olson',
        email: 'tj.olson@prisma.io',
        phone: '650.124.8234',
        hiredAt: new Date('1998-04-10'),
        jobId: 'ST_CLERK',
        salary: 2100,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 133,
        firstName: 'Jason',
        lastName: 'Mallin',
        email: 'jason.mallin@prisma.io',
        phone: '650.127.1934',
        hiredAt: new Date('1996-06-14'),
        jobId: 'ST_CLERK',
        salary: 3300,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 134,
        firstName: 'Michael',
        lastName: 'Rogers',
        email: 'michael.rogers@prisma.io',
        phone: '650.127.1834',
        hiredAt: new Date('1998-08-26'),
        jobId: 'ST_CLERK',
        salary: 2900,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 135,
        firstName: 'Ki',
        lastName: 'Gee',
        email: 'ki.gee@prisma.io',
        phone: '650.127.1734',
        hiredAt: new Date('1999-12-12'),
        jobId: 'ST_CLERK',
        salary: 2400,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 136,
        firstName: 'Hazel',
        lastName: 'Philtanker',
        email: 'hazel.philtanker@prisma.io',
        phone: '650.127.1634',
        hiredAt: new Date('2000-02-06'),
        jobId: 'ST_CLERK',
        salary: 2200,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 137,
        firstName: 'Renske',
        lastName: 'Ladwig',
        email: 'renske.ladwig@prisma.io',
        phone: '650.121.1234',
        hiredAt: new Date('1994-07-14'),
        jobId: 'ST_CLERK',
        salary: 3600,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 138,
        firstName: 'Stephen',
        lastName: 'Stiles',
        email: 'stephen.stiles@prisma.io',
        phone: '650.121.2034',
        hiredAt: new Date('1997-10-26'),
        jobId: 'ST_CLERK',
        salary: 3200,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 139,
        firstName: 'John',
        lastName: 'Seo',
        email: 'john.seo@prisma.io',
        phone: '650.121.2019',
        hiredAt: new Date('1998-02-12'),
        jobId: 'ST_CLERK',
        salary: 2700,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 140,
        firstName: 'Joshua',
        lastName: 'Patel',
        email: 'joshua.patel@prisma.io',
        phone: '650.121.1834',
        hiredAt: new Date('1999-04-06'),
        jobId: 'ST_CLERK',
        salary: 2500,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 141,
        firstName: 'Trenna',
        lastName: 'Rajs',
        email: 'trenna.rajs@prisma.io',
        phone: '650.121.8009',
        hiredAt: new Date('1995-10-17'),
        jobId: 'ST_CLERK',
        salary: 3500,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 142,
        firstName: 'Curtis',
        lastName: 'Davies',
        email: 'curtis.davies@prisma.io',
        phone: '650.121.2994',
        hiredAt: new Date('1997-01-29'),
        jobId: 'ST_CLERK',
        salary: 3100,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 143,
        firstName: 'Randall',
        lastName: 'Matos',
        email: 'randall.matos@prisma.io',
        phone: '650.121.2874',
        hiredAt: new Date('1998-03-15'),
        jobId: 'ST_CLERK',
        salary: 2600,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 144,
        firstName: 'Peter',
        lastName: 'Vargas',
        email: 'peter.vargas@prisma.io',
        phone: '650.121.2004',
        hiredAt: new Date('1998-07-09'),
        jobId: 'ST_CLERK',
        salary: 2500,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 145,
        firstName: 'John',
        lastName: 'Russell',
        email: 'john.russell@prisma.io',
        phone: '011.44.1344.429268',
        hiredAt: new Date('1996-10-01'),
        jobId: 'SA_MAN',
        salary: 14000,
        commissionPct: 0.4,
        managerId: 100,
        departmentId: 80,
      },
      {
        id: 146,
        firstName: 'Karen',
        lastName: 'Partners',
        email: 'karen.partners@prisma.io',
        phone: '011.44.1344.467268',
        hiredAt: new Date('1997-01-05'),
        jobId: 'SA_MAN',
        salary: 13500,
        commissionPct: 0.3,
        managerId: 100,
        departmentId: 80,
      },
      {
        id: 147,
        firstName: 'Alberto',
        lastName: 'Errazuriz',
        email: 'alberto.errazuriz@prisma.io',
        phone: '011.44.1344.429278',
        hiredAt: new Date('1999-03-10'),
        jobId: 'SA_MAN',
        salary: 12000,
        commissionPct: 0.3,
        managerId: 100,
        departmentId: 80,
      },
      {
        id: 148,
        firstName: 'Gerald',
        lastName: 'Cambrault',
        email: 'gerald.cambrault@prisma.io',
        phone: '011.44.1344.619268',
        hiredAt: new Date('1997-10-15'),
        jobId: 'SA_MAN',
        salary: 11000,
        commissionPct: 0.3,
        managerId: 100,
        departmentId: 80,
      },
      {
        id: 149,
        firstName: 'Eleni',
        lastName: 'Zlotkey',
        email: 'eleni.zlotkey@prisma.io',
        phone: '011.44.1344.429018',
        hiredAt: new Date('1998-01-29'),
        jobId: 'SA_MAN',
        salary: 10500,
        commissionPct: 0.2,
        managerId: 100,
        departmentId: 80,
      },
      {
        id: 150,
        firstName: 'Peter',
        lastName: 'Tucker',
        email: 'peter.tucker@prisma.io',
        phone: '011.44.1344.129268',
        hiredAt: new Date('1997-01-30'),
        jobId: 'SA_REP',
        salary: 10000,
        commissionPct: 0.3,
        managerId: 145,
        departmentId: 80,
      },
      {
        id: 151,
        firstName: 'David',
        lastName: 'Bernstein',
        email: 'david.bernstein@prisma.io',
        phone: '011.44.1344.345268',
        hiredAt: new Date('1997-03-24'),
        jobId: 'SA_REP',
        salary: 9500,
        commissionPct: 0.25,
        managerId: 145,
        departmentId: 80,
      },
      {
        id: 152,
        firstName: 'Peter',
        lastName: 'Hall',
        email: 'peter.hall@prisma.io',
        phone: '011.44.1345.829268',
        hiredAt: new Date('1996-08-20'),
        jobId: 'SA_REP',
        salary: 9000,
        commissionPct: 0.25,
        managerId: 145,
        departmentId: 80,
      },
      {
        id: 153,
        firstName: 'Christopher',
        lastName: 'Olsen',
        email: 'christopher.olsen@prisma.io',
        phone: '011.44.1343.929268',
        hiredAt: new Date('1997-03-30'),
        jobId: 'SA_REP',
        salary: 8000,
        commissionPct: 0.2,
        managerId: 145,
        departmentId: 80,
      },
      {
        id: 154,
        firstName: 'Nanette',
        lastName: 'Cambrault',
        email: 'nanette.cambrault@prisma.io',
        phone: '011.44.1343.529268',
        hiredAt: new Date('1998-12-09'),
        jobId: 'SA_REP',
        salary: 7500,
        commissionPct: 0.2,
        managerId: 145,
        departmentId: 80,
      },
      {
        id: 155,
        firstName: 'Oliver',
        lastName: 'Tuvault',
        email: 'oliver.tuvault@prisma.io',
        phone: '011.44.1343.929268',
        hiredAt: new Date('1999-11-23'),
        jobId: 'SA_REP',
        salary: 7000,
        commissionPct: 0.15,
        managerId: 145,
        departmentId: 80,
      },
      {
        id: 156,
        firstName: 'Janette',
        lastName: 'King',
        email: 'janette.king@prisma.io',
        phone: '011.44.1345.429268',
        hiredAt: new Date('2000-01-30'),
        jobId: 'SA_REP',
        salary: 10000,
        commissionPct: 0.35,
        managerId: 146,
        departmentId: 80,
      },
      {
        id: 157,
        firstName: 'Patrick',
        lastName: 'Sully',
        email: 'patrick.sully@prisma.io',
        phone: '011.44.1345.929268',
        hiredAt: new Date('1996-03-04'),
        jobId: 'SA_REP',
        salary: 9500,
        commissionPct: 0.35,
        managerId: 146,
        departmentId: 80,
      },
      {
        id: 158,
        firstName: 'Allan',
        lastName: 'McEwen',
        email: 'allan.mcewen@prisma.io',
        phone: '011.44.1345.829268',
        hiredAt: new Date('1997-08-01'),
        jobId: 'SA_REP',
        salary: 9000,
        commissionPct: 0.35,
        managerId: 146,
        departmentId: 80,
      },
      {
        id: 159,
        firstName: 'Lindsey',
        lastName: 'Smith',
        email: 'lindsey.smith@prisma.io',
        phone: '011.44.1345.729268',
        hiredAt: new Date('1997-03-10'),
        jobId: 'SA_REP',
        salary: 8000,
        commissionPct: 0.3,
        managerId: 146,
        departmentId: 80,
      },
      {
        id: 160,
        firstName: 'Louise',
        lastName: 'Doran',
        email: 'louise.doran@prisma.io',
        phone: '011.44.1345.629268',
        hiredAt: new Date('1998-12-15'),
        jobId: 'SA_REP',
        salary: 7500,
        commissionPct: 0.3,
        managerId: 146,
        departmentId: 80,
      },
      {
        id: 161,
        firstName: 'Sarath',
        lastName: 'Sewall',
        email: 'sarath.sewall@prisma.io',
        phone: '011.44.1345.529268',
        hiredAt: new Date('1999-11-03'),
        jobId: 'SA_REP',
        salary: 7000,
        commissionPct: 0.25,
        managerId: 146,
        departmentId: 80,
      },
      {
        id: 162,
        firstName: 'Clara',
        lastName: 'Vishney',
        email: 'clara.vishney@prisma.io',
        phone: '011.44.1346.129268',
        hiredAt: new Date('1997-11-11'),
        jobId: 'SA_REP',
        salary: 10500,
        commissionPct: 0.25,
        managerId: 147,
        departmentId: 80,
      },
      {
        id: 163,
        firstName: 'Danielle',
        lastName: 'Greene',
        email: 'danielle.greene@prisma.io',
        phone: '011.44.1346.229268',
        hiredAt: new Date('1999-03-19'),
        jobId: 'SA_REP',
        salary: 9500,
        commissionPct: 0.15,
        managerId: 147,
        departmentId: 80,
      },
      {
        id: 164,
        firstName: 'Mattea',
        lastName: 'Marvins',
        email: 'mattea.marvins@prisma.io',
        phone: '011.44.1346.329268',
        hiredAt: new Date('2000-01-24'),
        jobId: 'SA_REP',
        salary: 7200,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        id: 165,
        firstName: 'David',
        lastName: 'Lee',
        email: 'david.lee@prisma.io',
        phone: '011.44.1346.529268',
        hiredAt: new Date('1997-02-23'),
        jobId: 'SA_REP',
        salary: 6800,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        id: 166,
        firstName: 'Sundar',
        lastName: 'Ande',
        email: 'sundar.ande@prisma.io',
        phone: '011.44.1346.629268',
        hiredAt: new Date('2000-03-24'),
        jobId: 'SA_REP',
        salary: 6400,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        id: 167,
        firstName: 'Amit',
        lastName: 'Banda',
        email: 'amit.banda@prisma.io',
        phone: '011.44.1346.729268',
        hiredAt: new Date('1996-04-21'),
        jobId: 'SA_REP',
        salary: 6200,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        id: 168,
        firstName: 'Lisa',
        lastName: 'Ozer',
        email: 'lisa.ozer@prisma.io',
        phone: '011.44.1343.929268',
        hiredAt: new Date('1997-03-11'),
        jobId: 'SA_REP',
        salary: 11500,
        commissionPct: 0.25,
        managerId: 148,
        departmentId: 80,
      },
      {
        id: 169,
        firstName: 'Harrison',
        lastName: 'Bloom',
        email: 'harrison.bloom@prisma.io',
        phone: '011.44.1343.829268',
        hiredAt: new Date('1998-03-23'),
        jobId: 'SA_REP',
        salary: 10000,
        commissionPct: 0.2,
        managerId: 148,
        departmentId: 80,
      },
      {
        id: 170,
        firstName: 'Tayler',
        lastName: 'Fox',
        email: 'tayler.fox@prisma.io',
        phone: '011.44.1343.729268',
        hiredAt: new Date('1998-01-24'),
        jobId: 'SA_REP',
        salary: 9600,
        commissionPct: 0.2,
        managerId: 148,
        departmentId: 80,
      },
      {
        id: 171,
        firstName: 'William',
        lastName: 'Smith',
        email: 'william.smith@prisma.io',
        phone: '011.44.1343.629268',
        hiredAt: new Date('1999-02-23'),
        jobId: 'SA_REP',
        salary: 7400,
        commissionPct: 0.15,
        managerId: 148,
        departmentId: 80,
      },
      {
        id: 172,
        firstName: 'Elizabeth',
        lastName: 'Bates',
        email: 'elizabeth.bates@prisma.io',
        phone: '011.44.1343.529268',
        hiredAt: new Date('2000-03-24'),
        jobId: 'SA_REP',
        salary: 7300,
        commissionPct: 0.15,
        managerId: 148,
        departmentId: 80,
      },
      {
        id: 173,
        firstName: 'Sundita',
        lastName: 'Kumar',
        email: 'sundita.kumar@prisma.io',
        phone: '011.44.1343.329268',
        hiredAt: new Date('1995-08-21'),
        jobId: 'SA_REP',
        salary: 6100,
        commissionPct: 0.1,
        managerId: 148,
        departmentId: 80,
      },
      {
        id: 174,
        firstName: 'Ellen',
        lastName: 'Abel',
        email: 'ellen.abel@prisma.io',
        phone: '011.44.1644.429267',
        hiredAt: new Date('1996-05-11'),
        jobId: 'SA_REP',
        salary: 11000,
        commissionPct: 0.3,
        managerId: 149,
        departmentId: 80,
      },
      {
        id: 175,
        firstName: 'Alyssa',
        lastName: 'Hutton',
        email: 'alyssa.hutton@prisma.io',
        phone: '011.44.1644.429266',
        hiredAt: new Date('1997-03-19'),
        jobId: 'SA_REP',
        salary: 8800,
        commissionPct: 0.25,
        managerId: 149,
        departmentId: 80,
      },
      {
        id: 176,
        firstName: 'Jonathon',
        lastName: 'Taylor',
        email: 'jonathon.taylor@prisma.io',
        phone: '011.44.1644.429265',
        hiredAt: new Date('1998-03-24'),
        jobId: 'SA_REP',
        salary: 8600,
        commissionPct: 0.2,
        managerId: 149,
        departmentId: 80,
      },
      {
        id: 177,
        firstName: 'Jack',
        lastName: 'Livingston',
        email: 'jack.livingston@prisma.io',
        phone: '011.44.1644.429264',
        hiredAt: new Date('1999-04-23'),
        jobId: 'SA_REP',
        salary: 8400,
        commissionPct: 0.2,
        managerId: 149,
        departmentId: 80,
      },
      {
        id: 178,
        firstName: 'Kimberely',
        lastName: 'Grant',
        email: 'kimberely.grant@prisma.io',
        phone: '011.44.1644.429263',
        hiredAt: new Date('1999-05-24'),
        jobId: 'SA_REP',
        salary: 7000,
        commissionPct: 0.15,
        managerId: 149,
        departmentId: 80,
      },
      {
        id: 179,
        firstName: 'Charles',
        lastName: 'Johnson',
        email: 'charles.johnson@prisma.io',
        phone: '011.44.1644.429262',
        hiredAt: new Date('2000-01-04'),
        jobId: 'SA_REP',
        salary: 6200,
        commissionPct: 0.1,
        managerId: 149,
        departmentId: 80,
      },
      {
        id: 180,
        firstName: 'Winston',
        lastName: 'Taylor',
        email: 'winston.taylor@prisma.io',
        phone: '650.507.9876',
        hiredAt: new Date('1995-01-24'),
        jobId: 'SH_CLERK',
        salary: 3200,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 181,
        firstName: 'Jean',
        lastName: 'Fleaur',
        email: 'jean.fleaur@prisma.io',
        phone: '650.507.9877',
        hiredAt: new Date('1998-02-23'),
        jobId: 'SH_CLERK',
        salary: 3100,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 182,
        firstName: 'Martha',
        lastName: 'Sullivan',
        email: 'martha.sullivan@prisma.io',
        phone: '650.507.9878',
        hiredAt: new Date('1999-06-21'),
        jobId: 'SH_CLERK',
        salary: 2500,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 183,
        firstName: 'Girard',
        lastName: 'Geoni',
        email: 'girard.geoni@prisma.io',
        phone: '650.507.9879',
        hiredAt: new Date('1997-12-19'),
        jobId: 'SH_CLERK',
        salary: 2800,
        managerId: 120,
        departmentId: 50,
      },
      {
        id: 184,
        firstName: 'Nandita',
        lastName: 'Sarchand',
        email: 'nandita.sarchand@prisma.io',
        phone: '650.509.1876',
        hiredAt: new Date('1998-01-27'),
        jobId: 'SH_CLERK',
        salary: 4200,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 185,
        firstName: 'Alexis',
        lastName: 'Bull',
        email: 'alexis.bull@prisma.io',
        phone: '650.509.2876',
        hiredAt: new Date('1999-02-20'),
        jobId: 'SH_CLERK',
        salary: 4100,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 186,
        firstName: 'Julia',
        lastName: 'Dellinger',
        email: 'julia.dellinger@prisma.io',
        phone: '650.509.3876',
        hiredAt: new Date('1999-06-24'),
        jobId: 'SH_CLERK',
        salary: 3400,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 187,
        firstName: 'Anthony',
        lastName: 'Cabrio',
        email: 'anthony.cabrio@prisma.io',
        phone: '650.509.4876',
        hiredAt: new Date('2000-02-07'),
        jobId: 'SH_CLERK',
        salary: 3000,
        managerId: 121,
        departmentId: 50,
      },
      {
        id: 188,
        firstName: 'Kelly',
        lastName: 'Chung',
        email: 'kelly.chung@prisma.io',
        phone: '650.505.1876',
        hiredAt: new Date('1999-06-14'),
        jobId: 'SH_CLERK',
        salary: 3800,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 189,
        firstName: 'Jennifer',
        lastName: 'Dilly',
        email: 'jennifer.dilly@prisma.io',
        phone: '650.505.2876',
        hiredAt: new Date('1997-08-13'),
        jobId: 'SH_CLERK',
        salary: 3600,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 190,
        firstName: 'Timothy',
        lastName: 'Gates',
        email: 'timothy.gates@prisma.io',
        phone: '650.505.3876',
        hiredAt: new Date('1998-07-11'),
        jobId: 'SH_CLERK',
        salary: 2900,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 191,
        firstName: 'Randall',
        lastName: 'Perkins',
        email: 'randall.perkins@prisma.io',
        phone: '650.505.4876',
        hiredAt: new Date('1999-12-19'),
        jobId: 'SH_CLERK',
        salary: 2500,
        managerId: 122,
        departmentId: 50,
      },
      {
        id: 192,
        firstName: 'Sarah',
        lastName: 'Bell',
        email: 'sarah.bell@prisma.io',
        hiredAt: new Date('1996-02-04'),
        jobId: 'SH_CLERK',
        salary: 4000,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 193,
        firstName: 'Britney',
        lastName: 'Everett',
        email: 'britney@prisma.io',
        hiredAt: new Date('1997-03-03'),
        jobId: 'SH_CLERK',
        salary: 3900,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 194,
        firstName: 'Samuel',
        lastName: 'McCain',
        email: 'samuel.mccain@prisma.io',
        hiredAt: new Date('1998-07-01'),
        jobId: 'SH_CLERK',
        salary: 3200,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 195,
        firstName: 'Vance',
        lastName: 'Jones',
        email: 'vance.jones@prisma.io',
        hiredAt: new Date('1999-03-17'),
        jobId: 'SH_CLERK',
        salary: 2800,
        managerId: 123,
        departmentId: 50,
      },
      {
        id: 196,
        firstName: 'Alana',
        lastName: 'Walsh',
        email: 'alana.walsh@prisma.io',
        hiredAt: new Date('1998-04-24'),
        jobId: 'SH_CLERK',
        salary: 3100,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 197,
        firstName: 'Kevin',
        lastName: 'Feeney',
        email: 'kevin.feeney@prisma.io',
        hiredAt: new Date('1998-05-23'),
        jobId: 'SH_CLERK',
        salary: 3000,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 198,
        firstName: 'Donald',
        lastName: 'OConnell',
        email: 'donald.oconnell@prisma.io',
        hiredAt: new Date('1999-06-21'),
        jobId: 'SH_CLERK',
        salary: 2600,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 199,
        firstName: 'Douglas',
        lastName: 'Grant',
        email: 'douglas.grant@prisma.io',
        hiredAt: new Date('2000-01-13'),
        jobId: 'SH_CLERK',
        salary: 2600,
        managerId: 124,
        departmentId: 50,
      },
      {
        id: 200,
        firstName: 'Jennifer',
        lastName: 'Whalen',
        email: 'jennifer.whalen@prisma.io',
        hiredAt: new Date('1995-09-17'),
        jobId: 'AD_ASST',
        salary: 4400,
        managerId: 101,
        departmentId: 10,
      },
    ],
    skipDuplicates: true,
  });

  const jobhistories = await prisma.jobHistory.createMany({
    data: [
      {
        employeeId: 102,
        jobId: 'IT_PROG',
        departmentId: 60,
        startedAt: new Date('2001-09-17'),
        endedAt: new Date('2006-12-19'),
      },
      {
        employeeId: 101,
        jobId: 'AC_ACCOUNT',
        departmentId: 110,
        startedAt: new Date('2001-09-21'),
        endedAt: new Date('2005-12-31'),
      },
      {
        employeeId: 101,
        jobId: 'AC_MGR',
        departmentId: 110,
        startedAt: new Date('2006-01-01'),
        endedAt: new Date('2007-12-31'),
      },
      {
        employeeId: 201,
        jobId: 'MK_REP',
        departmentId: 20,
        startedAt: new Date('2006-02-10'),
        endedAt: new Date('2007-12-31'),
      },
      {
        employeeId: 114,
        jobId: 'ST_CLERK',
        departmentId: 50,
        startedAt: new Date('2007-01-01'),
        endedAt: new Date('2007-12-31'),
      },
      {
        employeeId: 122,
        jobId: 'ST_CLERK',
        departmentId: 50,
        startedAt: new Date('2007-01-01'),
        endedAt: new Date('2007-12-31'),
      },
      {
        employeeId: 200,
        jobId: 'AD_ASST',
        departmentId: 90,
        startedAt: new Date('2002-12-17'),
        endedAt: new Date('2006-07-24'),
      },
      {
        employeeId: 176,
        jobId: 'SA_REP',
        departmentId: 80,
        startedAt: new Date('2006-03-24'),
        endedAt: new Date('2006-12-31'),
      },
      {
        employeeId: 200,
        jobId: 'AC_ACCOUNT',
        departmentId: 90,
        startedAt: new Date('2007-01-01'),
        endedAt: new Date('2007-12-31'),
      },
    ],
    skipDuplicates: true,
  });

  console.log({
    regions,
    countries,
    locations,
    departments,
    jobs,
    employees,
    jobhistories,
  });

  const dept10 = await prisma.department.update({
    where: { id: 10 },
    data: {
      manager: {
        connect: { id: 200 },
      },
    },
  });

  const dept20 = await prisma.department.update({
    where: { id: 20 },
    data: {
      manager: {
        connect: { id: 101 },
      },
    },
  });

  const dept30 = await prisma.department.update({
    where: { id: 30 },
    data: {
      manager: {
        connect: { id: 114 },
      },
    },
  });

  const dept40 = await prisma.department.update({
    where: { id: 40 },
    data: {
      manager: {
        connect: { id: 114 },
      },
    },
  });

  const dept50 = await prisma.department.update({
    where: { id: 50 },
    data: {
      manager: {
        connect: { id: 121 },
      },
    },
  });

  const dept60 = await prisma.department.update({
    where: { id: 60 },
    data: {
      manager: {
        connect: { id: 103 },
      },
    },
  });

  const dept70 = await prisma.department.update({
    where: { id: 70 },
    data: {
      manager: {
        connect: { id: 113 },
      },
    },
  });

  const dept80 = await prisma.department.update({
    where: { id: 80 },
    data: {
      manager: {
        connect: { id: 145 },
      },
    },
  });

  const dept90 = await prisma.department.update({
    where: { id: 90 },
    data: {
      manager: {
        connect: { id: 100 },
      },
    },
  });

  const dept100 = await prisma.department.update({
    where: { id: 100 },
    data: {
      manager: {
        connect: { id: 108 },
      },
    },
  });

  console.log({
    dept10,
    dept20,
    dept30,
    dept40,
    dept50,
    dept60,
    dept70,
    dept80,
    dept90,
    dept100,
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
